version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 127214169103.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - docker build -t 127214169103.dkr.ecr.ap-south-1.amazonaws.com/codedeploy-ecr:latest .
      - mkdir -p build_output
      - cp appspec.yaml build_output/
      - cp taskdef.json build_output/
      - cp -r scripts build_output/

  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push 127214169103.dkr.ecr.ap-south-1.amazonaws.com/codedeploy-ecr:latest
      - echo "Build and push completed on `date`"

artifacts:
  files:
    - '**/*'
  base-directory: build_output
  discard-paths: no
